### ISSUE TITLE
yamllint is now installed by default on GitHub actions virtual environments

### ISSUE THREAD

**Issue by yvele** [ibiqlik/action-yamllint#10]
See https://github.com/actions/virtual-environments/issues/1142#issuecomment-672694799

and https://github.com/adrienverge/yamllint/issues/300

You probably don't need a custom Docket image anymore as yamllint already is installed by default 🤷

**Comment by ibiqlik** [comment]
@yvele NICE, I'll check it soon. If all is good, this action could potentially be converted to composite action and basically just serve as command line builder for running yamllint. On other hand docker image is good for use in self-hosted runners (though, one could argue that it's easier to preinstall software on self-hosted runners than GitHub provided ones)

**Comment by ibiqlik** [comment]
Doh, the version deployed is 1.10.0 which is a bit old and doesn't support some options, like -format and looks like it doesn't read .yamllint config by default. Investigation continues ...

**Comment by ibiqlik** [comment]
I think it is too unpredictable and somewhat disruptive to use pre-installed (outdated) yamllint. I'll create a `composite` branch have the action use pre-installed yamllint but not include in release, at least not yet.

**Comment by yvele** [comment]
Hey @ibiqlik it's fixed directly within GitHub Actions see https://github.com/actions/virtual-environments/issues/1657#issuecomment-717953802

**Comment by ibiqlik** [comment]
That's great news @yvele. I'm reopening the issue and will give it another take at composite action.
