### ISSUE TITLE
syntax errors where YAML is used with Helm templates

### ISSUE THREAD

**Issue by kaihendry** [ibiqlik/action-yamllint#21]
I have YAML in my repo with templating directives like

```
spec:
{{ $.Files.Get $rule | indent 2 }}
{{ end }}
```

How do people work around this?

**Comment by ibiqlik** [comment]
I think it is not possible to do a pure yaml lint on Helm templates as the template is not the final yaml output.
Personally I ignore `templates/` folder in .yamllint config like
```
ignore: |
  templates/
```
and if I have a Helm chart then I combine yaml lint with helm lint
`helm lint $DIR --with-subcharts`

**Comment by kaihendry** [comment]
Thank you for the hint. Do you recommend a helm lint action? Thank you again,

**Comment by ibiqlik** [comment]
Helm is pre-installed in the runners so you only need to have a run step like `- run: helm lint path/to/chart`.
Sometimes you need to prepare the chart before linting, like build dependencies, set a version or other operations then just expand the run to do that and exec helm lint at the end
```
- run: |
    helm dependency build path/to/chart
    helm lint path/to/chart
```
