### ISSUE TITLE
Output should be logged in a file

### ISSUE THREAD

**Issue by dhimanmohit2548** [ibiqlik/action-yamllint#22]
It would be nice to have this feature to log all the output in a file which can be easily attached to an email using another Github action. Currently the output is only in the console and no ways to capture it and log into a file. https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs

**Comment by ibiqlik** [comment]
@dhimanmohit2548 That's a great idea and easy to do. Should have something soon...

**Comment by ibiqlik** [comment]
@dhimanmohit2548 you want to give it a try https://github.com/ibiqlik/action-yamllint/pull/23?

You can test it like this: `uses: ibiqlik/action-yamllint@log-output`

**Comment by dhimanmohit2548** [comment]
@ibiqlik Thank you for prompt reply, sure will give it a try tomorrow morning. Much Appreciated 😊

**Comment by dhimanmohit2548** [comment]
@ibiqlik I tried using the branch but I am not able to see the contents of the file.

![image](https://user-images.githubusercontent.com/16471865/129156103-a0668503-0ec7-4c18-9c37-9dd2c82ccf91.png)

**Comment by ibiqlik** [comment]
@dhimanmohit2548 is `Dump outputs` step in the same job as `Check for lint errors` step or different? Because the file are not shared between steps unless you share them, see https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow

You can also see the run in that branch here https://github.com/ibiqlik/action-yamllint/runs/3293493615?check_suite_focus=true#step:6:1 and the workflow here https://github.com/ibiqlik/action-yamllint/blob/log-output/.github/workflows/lint.yml#L40

**Comment by dhimanmohit2548** [comment]
@ibiqlik its the part of the same job. Its just next step after the perform lint step. 
Also can we have the 
```
======================
= Linting YAML files =
======================
```
as part of the log file as well?

**Comment by dhimanmohit2548** [comment]
> @dhimanmohit2548 is `Dump outputs` step in the same job as `Check for lint errors` step or different? Because the file are not shared between steps unless you share them, see https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
> 
> You can also see the run in that branch here https://github.com/ibiqlik/action-yamllint/runs/3293493615?check_suite_focus=true#step:6:1 and the workflow here https://github.com/ibiqlik/action-yamllint/blob/log-output/.github/workflows/lint.yml#L40

I was encoding the variable output into double quotes. My Bad. Its working fine, thanks

**Comment by ibiqlik** [comment]
> @ibiqlik its the part of the same job. Its just next step after the perform lint step.
> Also can we have the
> 
> ```
> ======================
> = Linting YAML files =
> ======================
> ```
> 
> as part of the log file as well?

Capturing that is easy but as you can see in [this run](https://github.com/ibiqlik/action-yamllint/pull/23/checks?check_run_id=3310226568#step:6:6)  if you have multiple runs of yamllint it will capture for each one.
Also if you wanted to do something with the log like parse it, having that print will only make it more difficult

**Comment by atkaper** [comment]
Hi @ibiqlik I would love to have the output file option also ;-) I want to show the lint result as PR comment, so having that data will give me that option.

**Comment by ibiqlik** [comment]
Oh shoot, on it...
