### ISSUE TITLE
file_or_dir parameter doesn't accepts multiple files with space separated

### ISSUE THREAD

**Issue by dhimanmohit2548** [ibiqlik/action-yamllint#26]
I was trying to use the action `https://github.com/marketplace/actions/get-all-changed-files`  for the files changed and then using `ibiqlik/action-yamllint@log-output` but when supplied the output of the action `jitterbit/get-changed-files@v1` to the yaml lint it doesn't work.

![image](https://user-images.githubusercontent.com/16471865/129866754-484075ce-91c8-499f-ba49-a03394efa8aa.png)

**Comment by ibiqlik** [comment]
@dhimanmohit2548 Can confirm, the output is enclosed in singe quotes and yamllint is treating it as a single string/path. I'll take a look at this ASAP.

**Comment by dhimanmohit2548** [comment]
@ibiqlik  I tried with the following inputs:

`file_or_dir: ".github/workflows/blank.yml env/auto/ce.yml env/auto/gateway.yml env/auto/notifier.yml"`

`file_or_dir: '.github/workflows/blank.yml env/auto/ce.yml env/auto/gateway.yml env/auto/notifier.yml'`

`file_or_dir: .github/workflows/blank.yml env/auto/ce.yml env/auto/gateway.yml env/auto/notifier.yml`

`file_or_dir: "'.github/workflows/blank.yml env/auto/ce.yml env/auto/gateway.yml env/auto/notifier.yml'"`

for all these three inputs I received the same error

**[Errno 2] No such file or directory: '.github/workflows/blank.yml env/auto/ce.yml env/auto/gateway.yml env/auto/notifier.yml'**

![image](https://user-images.githubusercontent.com/16471865/129882770-50d1d695-b5d4-493a-a2f6-1fa79899edfb.png)

**Comment by ibiqlik** [comment]
@dhimanmohit2548 Can you please give it a try `uses: ibiqlik/action-yamllint@fix-path-input`?

**Comment by dhimanmohit2548** [comment]
@ibiqlik yes this one worked! Thanks!

![image](https://user-images.githubusercontent.com/16471865/129902872-bf5e0c17-6d64-4383-a6ae-96cd1eaa1569.png)

**Comment by ibiqlik** [comment]
Awesome, just made a release. Thanks for reporting it 🙇
