### ISSUE TITLE
`set-output` command is deprecated

### ISSUE THREAD

**Issue by yannbertrand** [ibiqlik/action-yamllint#32]
When running this action, this issue is logged:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

It seems quite new but the `set-output` usage should migrate to [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files).

Blog article explaining the change: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by ibiqlik** [comment]
Yeah, quite new but very annoying to see those warnings. Update imminent, thanks for reporting

**Comment by yannbertrand** [comment]
Upgraded on my side. Thanks a lot!
