### ISSUE TITLE
self-hosted runner entrypoint.sh: No such file or directory

### ISSUE THREAD

**Issue by dungpham91** [ibiqlik/action-yamllint#35]
Hi,

## Environment

I use actions on a self-hosted runner environment with containers on an EKS cluster environment.

## The error

I encountered the following error:

```
/__w/_temp/50d0d2e6-824d-4c0b-af54-03b73e83c507.sh: line 2: /runner/_work/_actions/ibiqlik/action-yamllint/v3/entrypoint.sh: No such file or directory
Error: Process completed with exit code 127.
```

## Description of the error

Before that, I ran actions with Github runner Ubuntu-latest and it was fine. However, when running the same workflows on a self-hosted environment with the container, an error will be encountered.

After some investigation and comparison between the two environments, I discovered something different about the action path when the runner uses it.

- Github runner with ubuntu-latest image:

![image](https://user-images.githubusercontent.com/75596049/198948035-a3dc4e08-ff56-46f1-9ccb-738e5d18a8fb.png)

- Self-hosted runner with ubuntu:latest image:

![image](https://user-images.githubusercontent.com/75596049/198948253-77544daa-027e-40d4-bd9b-7bd45a6b1059.png)

I tried investigating and found that file `entrypoint.sh` is located in the path `/__w/_actions/ibiqlik/action-yamllint/v3/entrypoint.sh` instead of `/runner/_work/_actions/ibiqlik/action-yamllint/v3/entrypoint.sh` as image above.

![image](https://user-images.githubusercontent.com/75596049/198949129-7125d771-0ce1-4ccf-860b-2598808e6f73.png)

## Error Cause

After researching, I learned that the cause of the file's path is so wrong because the values of the following two variables are different (it was used in file [action.yml](https://github.com/ibiqlik/action-yamllint/blob/master/action.yml) ):

- **`github.action_path`**: return the value `/runner/_work/_actions/ibiqlik/action-yamllint/v3/entrypoint.sh` with default path is `/runner/_work/_actions/`.
- **`GITHUB_ACTION_PATH`**: return the value `/__w/_actions/ibiqlik/action-yamllint/v3/entrypoint.sh` with default path is `/__w/_actions/`.

This bug has been identified on Github Runner [https://github.com/actions/runner/issues/716](https://github.com/actions/runner/issues/716).

## Solution

I created a PR about this bug and also added content to the `README.md` for instructions on using the self-hosted runner environment.

PR link: [https://github.com/ibiqlik/action-yamllint/pull/34](https://github.com/ibiqlik/action-yamllint/pull/34)

If you have time, go through it and test on your test environment. Thanks.

**Comment by ibiqlik** [comment]
@dungpham91 that is interesting, I have to admit I have not ran the action from a self-hosted runner. The question is if it is a better idea to move the content of the script as inline script in the aciton.yml file 🤔 ? I'll take a look at your PR

**Comment by dungpham91** [comment]
Yep, feel free to test my PR and try it on your test environment.

**Comment by mihai-sysbio** [comment]
I can confirm this is still an issue in `3.1.1`.
