### ISSUE TITLE
Proper version tagging

### ISSUE THREAD

**Issue by ruzickap** [ibiqlik/action-yamllint#5]
Hello.

Would it be possible to do a proper tagging for this project please? 

Maybe good starting point is here: https://github.com/actions/checkout 
They are using versions like:

* `v2` -> `v2.0.0`
* `v1` -> `v1.2.0`
* `v1.1.0`
* `v1.0.0`

It would be really handy to use something like `v1` instead of specifying the exact version only `v0.0.2`:

```yaml
    - uses: ibiqlik/action-yamllint@v1
```

It will save me from changing the "exact versions" or using "master" when you release new version.

For example this project can be handy for automating the release process: https://github.com/haya14busa/action-update-semver

Thank you...

**Comment by ibiqlik** [comment]
Yes, agree. It needs some love around the tagging/versioning. Will get to it soon.

**Comment by ruzickap** [comment]
Thank you...

PetrR
