### ISSUE TITLE
Ignore linting files in .git/

### ISSUE THREAD

**Issue by kenorb** [ibiqlik/action-yamllint#8]
```
Run ibiqlik/action-yamllint@master
  with:
    strict: true
    format: colored

======================
= Linting YAML files =
======================
./.git/refs/remotes/origin/optimize-strategy-ac.yml
  1:1       warning  missing document start "---"  (document-start)

./.git/logs/refs/remotes/origin/optimize-strategy-ac.yml
  1:121     warning  line too long (288 > 120 characters)  (line-length)
  1:176     error    syntax error: found character '\t' that cannot start any token (syntax)
```

Build: [869097594](https://github.com/EA31337/EA31337-Rider-optimization-tests/pull/5/checks?check_run_id=869097594#step:4:9)

It seems action is trying to lint files within `.git` it-self. Can this be disabled by default?

**Comment by ibiqlik** [comment]
By default `yamllint` checks every .yaml file in the path. To ignore certain paths you have two options

1. Recommended: Add `.yamllint` file in your root git repository and set your desired behavior, like ignoring paths, setting rules etc.
```yaml
---
extends: default

ignore: |
  .git
  /ignore/my/other/dir/
```

2. Use `config_data` in the GitHub action to specify configuration
```yaml
- uses: ibiqlik/action-yamllint@v1
  with:
    config_data: "{extends: default, ignore: .git}"
```

For more details on specific configuration of yamllint itself please refer to documentation, for this specific question look here https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths

**Comment by kenorb** [comment]
Thanks, I'll test suggested approach.

**Comment by timmc-edx** [comment]
I'd suggest reopening this. It occurs when someone creates a branch with a name ending in `.yml`. Git then creates a ref file in its internal storage under `.git/` and the file path ends with the branch name.

I don't think a yamllint GH action should be processing .git internal files in any case.
